from cassandra.cluster import Cluster
from cassandra.auth import PlainTextAuthProvider
import json
import csv

# This secure connect bundle is autogenerated when you download your SCB, 
# if yours is different update the file name below
cloud_config= {
  'secure_connect_bundle': 'secure-connect-traffic-db.zip'
}

# This token JSON file is autogenerated when you download your token, 
# if yours is different update the file name below
with open("traffic_db-token.json") as f:
    secrets = json.load(f)

CLIENT_ID = secrets["clientId"]
CLIENT_SECRET = secrets["secret"]

auth_provider = PlainTextAuthProvider(CLIENT_ID, CLIENT_SECRET)
cluster = Cluster(cloud=cloud_config, auth_provider=auth_provider)
session = cluster.connect()

row = session.execute('SELECT * FROM "interstatetraffic_db"."data_trafficVolume" LIMIT 10')
if row:
    # Specify the CSV file path
    csv_file_path = 'output.csv'

    # Write named tuples to CSV file
    with open(csv_file_path, 'w', newline='') as csv_file:
        writer = csv.writer(csv_file)
        
        # Write header
        writer.writerow(row[0]._fields)
        
        # Write data
        for each in row:
            writer.writerow(each)
else:
  print("An error occurred.")